# This is how to change logging level in spring boot
#logging:
#  level:
#    org.elasticsearch: DEBUG
---

# This is how to enable http access for elastic search
#spring.data.elasticsearch.properties.http.enabled: true
---
server:
  port: 8081